server:
  port: 9001

spring:
  application:
    name: blp-auth
  datasource:
    url: jdbc:mysql://localhost:3306/blp_db?useUnicode=true&characterEncoding=utf8mb4&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

knife4j:
  enable: true
  setting:
    language: zh_cn

logging:
  level:
    com.blp.auth: DEBUG
