server:
  port: 9005

spring:
  application:
    name: blp-cart
  data:
    redis:
      host: localhost
      port: 6379
      password: redis
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

knife4j:
  enable: true
